"""How long a render will take, said honestly — and better every time.

His correction, verbatim: JARVIS should give an estimate and then ASK whether to
proceed, "because maybe I don't want to do it if it's going to take over an
hour". That only works if the estimate is worth hearing. A number invented at
the moment of asking is worse than no number, because he will plan around it.

SO: A CONSERVATIVE SEED, THEN MEASUREMENT. Each tier starts with a seed drawn
from what the technique costs on this class of hardware, deliberately on the
pessimistic side — being told ninety seconds and waiting sixty is a pleasant
surprise; being told sixty and waiting ninety is a broken promise. After the
first real run the seed stops being used and the estimate is the MEDIAN of the
last few measured durations on this machine.

MEDIAN, NOT MEAN. One render that hit a cold model load and took four minutes
should not drag every subsequent estimate upwards for the rest of the day. The
median ignores it; the mean would carry it forever.

Persisted as JSON beside the database rather than in it. This is a handful of
floats that can be regenerated by using the feature, and it must never be able
to hold a write lock on the one file every turn goes through — the bookkeeping
that killed every turn on 2026-08-31 was exactly that shape.
"""
from __future__ import annotations

import json
import logging
import statistics
import time

from config import APP_DIR, config

log = logging.getLogger("jarvis.render.estimates")

# Seconds. Pessimistic on purpose; replaced by measurement after one real run.
#
#   1  the model writes OpenSCAD and OpenSCAD renders it — two seconds of
#      generation on a warm llama-server, plus a render
#   2  an image traced to a contour and extruded: OpenCV and OpenSCAD, no model
#   3  a photo to a mesh (TripoSR). MEASURED: 18.8 s inside the worker — 3.8 s to
#      load, 2.3 s to cut the background out on the 780M, 9.4 s of reconstruction
#      and 3.3 s of marching cubes — and 32.8 s end to end THROUGH THE SIDECAR,
#      because starting the subprocess and importing torch is most of the
#      difference. The seed is the end-to-end number, since that is the one he
#      waits for.
#   4  the same, with a web image search and a download in front of it
#
# TIER 1 WAS SEEDED AT 8 s AND MEASURED AT 28. I had reasoned that OpenSCAD is
# fast and set the seed under the ask threshold so it would never interrupt him;
# the first real run on this machine took 27.97 seconds, because the slow part is
# not OpenSCAD at all — it is llama-server writing the source. So the seed is the
# measurement now, and tier 1 asks, which is right: half a minute of waiting
# deserves a heads-up, and the threshold exists to skip the question for things
# that are genuinely instant.
#
# TIER 2 is the one that stays under it, and honestly so: tracing a contour and
# extruding it involves no model at all.
# Tier 0 is a template and a render, with no model in the loop at all. Measured
# at 0.12-0.30 s on this machine; seeded at 2 s so a cold OpenSCAD start is still
# inside it, and comfortably under the ask threshold — nobody wants to be asked
# permission to spend a fifth of a second.
SEED = {0: 2.0, 1: 25.0, 2: 6.0, 3: 35.0, 4: 55.0, 5: 45.0}

KEEP = 9                       # how many measured runs count toward the median
_PATH = APP_DIR / "render_times.json"


def _load() -> dict:
    try:
        raw = json.loads(_PATH.read_text(encoding="utf-8"))
        return {int(k): [float(x) for x in v][-KEEP:] for k, v in raw.items()}
    except Exception:
        return {}


def _save(data: dict) -> None:
    try:
        _PATH.write_text(json.dumps({str(k): v for k, v in data.items()}),
                         encoding="utf-8")
    except OSError:
        log.debug("could not save render times", exc_info=True)


def estimate(tier: int) -> float:
    """Seconds this tier is expected to take, measured if it ever has been."""
    seen = _load().get(int(tier)) or []
    if not seen:
        return float(SEED.get(int(tier), 60.0))
    return float(statistics.median(seen))


def measured(tier: int) -> int:
    """How many real runs this estimate rests on. 0 means it is still the seed."""
    return len(_load().get(int(tier)) or [])


def record(tier: int, seconds: float) -> None:
    """A real duration, measured on this machine."""
    if seconds <= 0:
        return
    data = _load()
    runs = data.get(int(tier)) or []
    runs.append(round(float(seconds), 2))
    data[int(tier)] = runs[-KEEP:]
    _save(data)


def ask_threshold() -> float:
    """Above this many seconds, ask before starting. Config, not a constant.

    Under it JARVIS simply does the thing and reports — asking permission to
    spend three seconds is friction, not courtesy.
    """
    return float(config.get("fabrication", "ask_above_seconds", default=10))


def spoken(seconds: float) -> str:
    """A duration as a person says it. Never "about 74.3 seconds"."""
    s = max(0.0, float(seconds))
    if s < 10:
        return "a few seconds"
    if s < 45:
        return f"about {int(round(s / 5.0) * 5)} seconds"
    if s < 90:
        return "about a minute"
    if s < 150:
        return "a couple of minutes"
    if s < 3300:
        mins = int(round(s / 60.0))
        return f"about {mins} minutes"
    hours = s / 3600.0
    if hours < 1.25:
        return "the better part of an hour"
    if hours < 1.75:
        return "about an hour and a half"
    return f"about {int(round(hours))} hours"


def confidence_note(tier: int) -> str:
    """Said once, while the estimate is still a guess rather than a measurement.

    Being told "about a minute" by something that has never done it before, and
    then waiting four, is how an estimate stops being believed. Saying so costs
    six words.
    """
    return "" if measured(tier) else " — though I've not done one of these before"


class Timer:
    """Times a render and files the result under its tier."""

    def __init__(self, tier: int) -> None:
        self.tier = int(tier)
        self.t0 = time.time()

    @property
    def elapsed(self) -> float:
        return time.time() - self.t0

    def done(self) -> float:
        took = self.elapsed
        record(self.tier, took)
        return took
